name: Bot Log
on: 
  schedule:
    - cron: '0 21 * * *'
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  log:
    runs-on: Ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Setup Deploy Private Key
      env:
        BOT_DEPLOY_KEY: ${{ secrets.BOT_DEPLOY_KEY }}
        BOT_NAME: ${{ secrets.BOT_NAME }}
        BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
      run: |
        mkdir -p ~/.ssh/
        echo "$Bot_DEPLOY_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "$BOT_EMAIL"
        git config --global user.name "$BOT_NAME"
    - name: Bot Log
      run: |
        Date=`date -d '+0 hours' +'%Y-%m-%d %H:%M:%S'`
        echo "[$Date] Successful" >> readme.md

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.BOT_DEPLOY_KEY }}
        user_name: ${{ secrets.BOT_NAME }}
        user_email: ${{ secrets.BOT_EMAIL }}
        publish_dir: ./
        publish_branch: botlog
